# Development Configuration for smolval
# Fast, cost-effective setup for local development and testing

mcp_servers:
  # Basic filesystem server for testing file operations
  - name: "filesystem"
    command: ["npx", "@modelcontextprotocol/server-filesystem", "."]
    env: {}

  # Web content fetching for testing HTTP operations
  - name: "fetch"
    command: ["uvx", "mcp-server-fetch"]
    env:
      USER_AGENT: "smolval-dev"

llm:
  # Use Claude Haiku for faster, cheaper development
  provider: "anthropic"
  model: "claude-3-haiku-20240307"
  api_key: "${ANTHROPIC_API_KEY}"
  temperature: 0.1
  max_tokens: 4096

evaluation:
  # Shorter timeouts for quick feedback
  timeout_seconds: 60
  max_iterations: 10
  output_format: "markdown"
  results_dir: "dev-results"
  
  # Enable debug logging for development
  log_level: "DEBUG"
  include_timestamps: true
  include_performance_metrics: true