# Simple Claude Code configuration using built-in tools
# No MCP servers needed for basic filesystem/bash operations

mcp_servers: []  # Use Claude Code's built-in tools
allow_empty_servers: true  # Allow empty MCP server list for Claude Code

llm:
  provider: "anthropic"
  model: "claude-3-5-sonnet-20241022"
  api_key: "${ANTHROPIC_API_KEY}"
  temperature: 0.1
  max_tokens: 4096

evaluation:
  timeout_seconds: 120
  max_iterations: 15  # Not used by Claude Code agent
  output_format: "markdown"
  agent_type: "claude_code"  # Use Claude Code instead of ReAct agent

judge:
  enabled: false