mcp_servers:
  # No API key required - basic file operations
  - name: "filesystem"
    command: ["npx", "@modelcontextprotocol/server-filesystem", "."]
    env: {}
  
  # No API key required - web content fetching
  - name: "fetch"
    command: ["uvx", "mcp-server-fetch"]
    env: {}
  
  # No API key required - local database (Docker-based)
  # - name: "sqlite"
  #   command: ["docker", "run", "--rm", "-i", "mcp/sqlite", "--db-path", "/tmp/data.db"]
  #   env: {}

  # Optional servers requiring API keys (comment out if not needed)
  # - name: "brave_search" 
  #   command: ["npx", "@modelcontextprotocol/server-brave-search"]
  #   env:
  #     BRAVE_API_KEY: "${BRAVE_API_KEY}"
  # - name: "github"
  #   command: ["npx", "@modelcontextprotocol/server-github"]
  #   env:
  #     GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_TOKEN}"

llm:
  provider: "anthropic"
  model: "claude-4-sonnet"  # Latest Claude 4 Sonnet
  # Alternative models:
  # model: "claude-3.7-sonnet-latest"  # Claude 3.7 Sonnet
  # model: "claude-3.5-sonnet-latest"  # Claude 3.5 Sonnet
  api_key: "${ANTHROPIC_API_KEY}"  # Set ANTHROPIC_API_KEY environment variable
  temperature: 0.1

evaluation:
  timeout_seconds: 60
  max_iterations: 10