mcp_servers:
  - name: "filesystem"
    command: ["npx", "@modelcontextprotocol/server-filesystem", "."]
    env: {}
  - name: "honeycomb"
    command:
      [
        "npx",
        "mcp-remote",
        "https://mcp.honeycomb.io/sse",
        "--header",
        "Authorization: Bearer ${HONEYCOMB_API_KEY}",
      ]
    env:
      {
        HONEYCOMB_API_KEY: "${HONEYCOMB_API_KEY}",
      }

llm:
  provider: "openai"
  model: "gpt-4.1"  # Latest GPT-4o model
  # Alternative models:
  # model: "gpt-4o-mini"  # Smaller, faster GPT-4o
  # model: "gpt-4-turbo"  # GPT-4 Turbo
  api_key: "${OPENAI_API_KEY}"  # Set OPENAI_API_KEY environment variable
  temperature: 0.1
evaluation:
  timeout_seconds: 120 # Longer timeout for complex analysis
  max_iterations: 15 # More iterations for thorough analysis
