mcp_servers:
  - name: "filesystem"
    command: ["npx", "@modelcontextprotocol/server-filesystem", "."]
    env: {}
  - name: "honeycomb"
    command:
      [
        "npx",
        "mcp-remote",
        "https://mcp.honeycomb.io/sse",
        "--header",
        "Authorization: Bearer ${HONEYCOMB_API_KEY}",
      ]
    env:
      {
        HONEYCOMB_API_KEY: "${HONEYCOMB_API_KEY}",
      }

llm:
  provider: "gemini"
  model: "gemini-2.5-pro-preview-05-06"
  # Alternative models:
  # model: "gemini-2.5-flash-preview-04-17"  # Gemini 2.5 Flash preview
  # model: "gemini-1.5-pro-latest"  # Gemini 1.5 Pro latest
  # model: "gemini-1.5-flash-latest"  # Gemini 1.5 Flash latest
  api_key: "${GEMINI_API_KEY}"  # Set GEMINI_API_KEY environment variable (or LLM_GEMINI_KEY)
  temperature: 0.1

evaluation:
  timeout_seconds: 120 # Longer timeout for complex analysis
  max_iterations: 15 # More iterations for thorough analysis
