mcp_servers:
  # Filesystem server for basic file operations
  - name: "filesystem"
    command: ["npx", "@modelcontextprotocol/server-filesystem", "/tmp"]
    env: {}
  
  # Memory server for persistent knowledge storage
  - name: "memory"
    command: ["npx", "@modelcontextprotocol/server-memory"]
    env: {}
  
  # SQLite server for local database operations (via Docker)
  - name: "sqlite"
    command: ["docker", "run", "--rm", "-i", "-v", "mcp-test:/mcp", "mcp/sqlite", "--db-path", "/mcp/test.db"]
    env: {}

llm:
  provider: "openai"
  model: "gpt-4o-mini"  # GPT-4o Mini
  api_key: "${OPENAI_API_KEY}"  # Set this environment variable
  temperature: 0.1

evaluation:
  timeout_seconds: 120
  max_iterations: 15
  output_format: "json"