name: Integration Tests

permissions:
  contents: read
  actions: read

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    # Run integration tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python 3.12
      run: uv python install 3.12
    
    - name: Install dependencies
      run: |
        uv sync --all-extras
    
    - name: Install Node.js for MCP servers
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install MCP servers
      run: |
        npm install -g @modelcontextprotocol/server-filesystem
    
    - name: Test CLI with real evaluation
      run: |
        # Test simple evaluation with built-in tools only
        uv run python -m smolval.cli eval prompts/simple_test.txt --format json --output test_results.json --verbose
        # Test with different output format
        uv run python -m smolval.cli eval prompts/simple_test.txt --format markdown --output test_results.md --verbose
        # Test with MCP tools allowed
        uv run python -m smolval.cli eval prompts/simple_test.txt --format html --output test_results.html --allowed-tools "mcp__filesystem" --verbose
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results
        path: |
          test_results.json
          test_results.md
          test_results.html
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "CLI integration tests failed. Check the logs for details."
        echo "This could indicate issues with Claude Code CLI or API connectivity."